spring:
  application:
    name: swallowincense-auth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
  redis:
    host: 192.168.159.128
    port: 6379
    password: liuyang
  session:
    store-type: redis
server:
  port: 20000
  servlet:
    session:
      timeout: 30m